service: nuxt-ssr
plugins: 
  - serverless-offline

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1

functions:
  nuxt-ssr:
    handler: lambda.handler
    timeout: 30
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'